name = "github-interaction"
account_id = ""
workers_dev = true
main = "src/index.ts"
compatibility_date = "2023-02-11"

[vars]
DEFAULT_REPO = ""
DEFAULT_REPO_OWNER = ""
DISCORD_PUBLIC_KEY = ""
GITHUB_TOKEN = ""
